name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build image for scan
        run: |
          docker build \
            -f microservice/Dockerfile \
            -t go-microservice:scan \
            microservice

      - name: Scan image with Trivy Action
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: go-microservice:ci
          format: table
          exit-code: 1
          sev-list: CRITICAL,HIGH

