# .github/workflows/security-scan.yml
name: Build & Security Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build \
            --tag go-microservice:ci .

      - name: Save image to TAR
        run: |
          docker save go-microservice:ci \
            --output image.tar

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release ca-certificates
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key \
            | sudo gpg --dearmor -o /usr/share/keyrings/trivy-archive-keyring.gpg
          echo \
            "deb [signed-by=/usr/share/keyrings/trivy-archive-keyring.gpg] \
            https://aquasecurity.github.io/trivy-repo/deb \
            $(lsb_release -sc) main" \
            | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Scan image.tar with Trivy
        run: |
          trivy image \
            --input image.tar \
            --exit-code 1 \
            --severity HIGH,CRITICAL
