# .github/workflows/security-scan.yml
name: Build & Security Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build \
            -f microservice/Dockerfile \
            -t go-microservice:ci \
            microservice

      - name: Scan image with Trivy Action
        uses: aquasecurity/trivy-action@v0.8.0
        with:
          image-ref: go-microservice:ci
          format: table
          exit-code: 1         # falla si hay HIGH/CRITICAL
          sev-list: CRITICAL,HIGH
